### ISSUE TITLE
Ruby documentation is in Japanese

### ISSUE THREAD

**Issue by jamesgecko** [xord/rubysketch_ios#8]
The application and bundled Processing documentation are in English, but the Ruby "reference manual" and "library reference" menu items link to an external website in Japanese.

**Comment by xord** [comment]
@jamesgecko Thanks for the feedback.
We were able to fix it in our development environment here, so please wait for the next version of RubySketch!

**Comment by xord** [comment]
RubySketch 2.10 with fixed bugs is now available on the AppStore.
Please check it out.

**Comment by xord** [comment]
@jamesgecko RubySketch 2.10 with fixed bugs is now available on the AppStore.
Please check it out.
